# Generated by Django 2.2.5 on 2020-02-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
    ]
